### PR TITLE
feat: add gitmoji as convention

### LINKED ISSUE #33: Adding gitmoji as convention
## Proposal
What do you think about adding gitmoji as convention type (https://gitmoji.dev/)
I can work on this if you want.

## Motivation
Lots of repositories are now using gitmoji for their commits

## Use cases and examples
All-contributors bot is using commit-conv to generate commit-message

### PR DESCRIPTION
**Pull request by bengeois**
## Checklist

-   [x] The PR follows the [guidelines](CONTRIBUTING.md)
-   [x] Passes all the tests (including added/updated ones)
-   [x] Contains a valid documentation
-   [x] It's not a duplicate from another PR

## Changes
This PR implements:
-   [x] Feature

## Details
What does this PR implements exactly?

Closes https://github.com/Berkmann18/commit-conv/issues/33

### CODE REVIEW

**Comment by bengeois** [comment]
@Berkmann18 That would be great if you can tag your repo with "hacktoberfest" tag :)

**Comment by Berkmann18** [comment]
@all-contributors please add @bengeois for code

**Comment by bengeois** [comment]
Thanks @Berkmann18, do you plan a release ?

**Comment by Berkmann18** [comment]
> Thanks @Berkmann18, do you plan a release ?

It should be automatically released at some point and the bot comments on PRs that were part of a release.

There might be something wrong with the deployment. I'll check when I have time.

**Pull request merged**
